# http://module-build.sourceforge.net/META-spec.html
name:         String-CamelCase
version:      0.02
version_from: lib/String/CamelCase.pm
installdirs:  site
author:       YAMASHINA Hio <hio@cpan.org>
abstract:     camelcase, de-camelcase
license:      perl
requires:
  Test::More: 0
#build_requires:
no_index:
  directory:
    - inc
    - t

distribution_type: module
generated_by: ExtUtils::MY_Metafile version 0.09, EUMM-6.17.
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
